#!/bin/bash

SERVER=( '62.65.153.121' )

ENVIRONMENT=${1:-"production"}
REF=${2:-"master"}

DEPLOY_PATH=/home/user/inweso

#REPO=user@your_repository_url.git
USER=user

trap 'test -n "$SUCCESS" || echo "  error: aborted"' EXIT
echo "* Deploying $ENVIRONMENT/$REF to $DEPLOY_PATH"

ssh -t $USER@$SERVER "cd $DEPLOY_PATH && \
				   sudo stop inweso && \
                   git pull && \
                   npm install && \
                   sudo start inweso"

#ssh $USER@$SERVER "cd $DEPLOY_PATH && \
#                   git reset --hard && \
#                   git checkout $REF && \
#                   git pull && \
#                   npm install && \
#                   /etc/init.d/your_app stop"

SUCCESS=true